routes:
  - name: user_service
    context: /api/v1/users
    target: http://user_service:8080
  - name: auth_service
    context: /auth
    target: http://user_service:8080
  - name: flashcard_service
    context: /api/v1/category
    target: http://flashcard_service:9090